AWSTemplateFormatVersion: 2010-09-09
Description: Optional Bastion Host setup to access the private servers for debugging
Parameters: 
  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String
  SecurityKey:
    Description: Bastion Host security key
    Type: String
  MyIPAddress:
    Description: IPAddress of my local machine
    Type: String
  AMItoUse:
    Description: Ubuntu 18.04 LTS image to use for the EC2 instance
    Type: String
  EC2InstanceType:
    Description: Instance type of the EC2 instance
    Type: String

Resources: 
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SecurityKey
      ImageId: !Ref AMItoUse
      InstanceType: !Ref EC2InstanceType
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet: 
            - !Ref BastionHostSecurityGroup
          SubnetId: 
            Fn::ImportValue: !Sub ${EnvironmentName}-Public1-SN
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-BastionHost
  
  BastionHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Bastion Host
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIPAddress
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-BastionHost-SG